package cfd.ghostbin.ghostwebvpn

import android.content.Intent
import android.net.VpnService
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.app.AlertDialog
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import java.util.Locale

/**
 * Ghost Web VPN for Android: import a WireGuard peer config generated by the
 * Ghost endpoint, connect with one tap, and watch live tunnel stats.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var repo: TunnelRepository

    private lateinit var statusLabel: TextView
    private lateinit var connectButton: Button
    private lateinit var statsBox: LinearLayout
    private lateinit var statsLabel: TextView
    private lateinit var removeButton: Button
    private lateinit var builderCard: LinearLayout
    private lateinit var builderSummary: TextView
    private lateinit var editKey: EditText
    private lateinit var editAddress: EditText
    private lateinit var editDns: EditText
    private lateinit var editServerKey: EditText
    private lateinit var editEndpoint: EditText
    private lateinit var editAllowedIps: EditText
    private lateinit var editConfigText: EditText

    private var statsJob: Job? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        VpnManager.initialize(applicationContext)
        repo = VpnManager.repository()
        setContentView(R.layout.activity_main)
        bindViews()
        restoreSavedConfig()
        updateUi(VpnManager.state.value)
        observeState()
    }

    private fun bindViews() {
        statusLabel = findViewById(R.id.status_label)
        connectButton = findViewById(R.id.connect_button)
        statsBox = findViewById(R.id.stats_box)
        statsLabel = findViewById(R.id.stats_label)
        removeButton = findViewById(R.id.remove_button)
        builderCard = findViewById(R.id.builder_card)
        builderSummary = findViewById(R.id.builder_summary)
        editKey = findViewById(R.id.edit_private_key)
        editAddress = findViewById(R.id.edit_address)
        editDns = findViewById(R.id.edit_dns)
        editServerKey = findViewById(R.id.edit_server_key)
        editEndpoint = findViewById(R.id.edit_endpoint)
        editAllowedIps = findViewById(R.id.edit_allowed_ips)
        editConfigText = findViewById(R.id.edit_config_text)

        connectButton.setOnClickListener { onConnectClicked() }
        findViewById<Button>(R.id.generate_keys_button).setOnClickListener { onGenerateKeys() }
        findViewById<Button>(R.id.import_config_button).setOnClickListener { onImportConfig() }
        findViewById<Button>(R.id.save_config_button).setOnClickListener { onSaveConfig() }
        removeButton.setOnClickListener { onRemoveConfig() }
    }

    private fun observeState() {
        lifecycleScope.launch {
            VpnManager.state.collect { updateUi(it) }
        }
    }

    private fun updateUi(state: VpnState) {
        statusLabel.setText(
            when (state) {
                VpnState.DISCONNECTED -> R.string.status_disconnected
                VpnState.CONNECTING -> R.string.status_connecting
                VpnState.CONNECTED -> R.string.status_connected
                VpnState.FAILED -> R.string.status_failed
            }
        )
        connectButton.setText(
            if (state == VpnState.CONNECTED) R.string.disconnect else R.string.connect
        )
        connectButton.isEnabled = state != VpnState.CONNECTING
        val showStats = state == VpnState.CONNECTED
        statsBox.visibility = if (showStats) View.VISIBLE else View.GONE
        if (showStats) startStatsPolling() else statsJob?.cancel()
    }

    private fun startStatsPolling() {
        if (statsJob?.isActive == true) return
        statsJob = lifecycleScope.launch {
            while (isActive) {
                val stats = VpnManager.stats()
                if (stats != null) {
                    val handshake = if (stats.handshakeEpochMs > 0L) {
                        val secondsAgo = (System.currentTimeMillis() - stats.handshakeEpochMs) / 1000
                        getString(R.string.handshake_ago, secondsAgo)
                    } else {
                        getString(R.string.handshake_none)
                    }
                    statsLabel.text = getString(
                        R.string.stats_format,
                        formatBytes(stats.totalRx),
                        formatBytes(stats.totalTx),
                        handshake
                    )
                }
                delay(1000)
            }
        }
    }

    private fun onConnectClicked() {
        if (VpnManager.state.value == VpnState.CONNECTED) {
            lifecycleScope.launch { VpnManager.disconnect() }
            return
        }
        if (repo.loadConfig() == null) {
            Toast.makeText(this, R.string.no_config, Toast.LENGTH_LONG).show()
            builderCard.visibility = View.VISIBLE
            return
        }
        // The system VPN consent dialog is required before the first connect.
        val consentIntent = VpnService.prepare(this)
        if (consentIntent != null) {
            startActivityForResult(consentIntent, REQUEST_VPN_CONSENT)
        } else {
            lifecycleScope.launch { VpnManager.connect() }
        }
    }

    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_VPN_CONSENT) {
            if (resultCode == RESULT_OK) {
                lifecycleScope.launch { VpnManager.connect() }
            } else {
                Toast.makeText(this, R.string.vpn_permission_denied, Toast.LENGTH_LONG).show()
            }
        }
    }

    private fun onGenerateKeys() {
        val (privateKey, publicKey) = TunnelRepository.generateKeypair()
        editKey.setText(privateKey)
        Toast.makeText(
            this,
            getString(R.string.public_key_copied, publicKey),
            Toast.LENGTH_LONG
        ).show()
    }

    private fun onImportConfig() {
        val text = editConfigText.text.toString()
        if (text.isBlank()) {
            Toast.makeText(this, R.string.paste_config_first, Toast.LENGTH_SHORT).show()
            return
        }
        val fields = TunnelRepository.parseWgQuickFields(text)
        fields[TunnelRepository.FIELD_PRIVATE_KEY]?.let { editKey.setText(it) }
        fields[TunnelRepository.FIELD_ADDRESS]?.let { editAddress.setText(it) }
        fields[TunnelRepository.FIELD_DNS]?.let { editDns.setText(it) }
        fields[TunnelRepository.FIELD_PEER_PUBLIC_KEY]?.let { editServerKey.setText(it) }
        fields[TunnelRepository.FIELD_ENDPOINT]?.let { editEndpoint.setText(it) }
        fields[TunnelRepository.FIELD_ALLOWED_IPS]?.let { editAllowedIps.setText(it) }
        Toast.makeText(this, R.string.config_imported, Toast.LENGTH_SHORT).show()
    }

    private fun onSaveConfig() {
        val privateKey = editKey.text.toString().trim()
        val address = editAddress.text.toString().trim()
        val serverKey = editServerKey.text.toString().trim()
        val endpoint = editEndpoint.text.toString().trim()
        val allowedIps = editAllowedIps.text.toString().trim()

        if (privateKey.isEmpty() || address.isEmpty() || serverKey.isEmpty() ||
            endpoint.isEmpty() || allowedIps.isEmpty()
        ) {
            Toast.makeText(this, R.string.fill_required_fields, Toast.LENGTH_LONG).show()
            return
        }

        val wgQuick = TunnelRepository.buildWgQuickConfig(
            privateKey = privateKey,
            address = address,
            dns = editDns.text.toString().trim().ifBlank { null },
            serverPublicKey = serverKey,
            endpoint = endpoint,
            allowedIps = allowedIps
        )
        val config = runCatching { com.wireguard.config.Config.parse(wgQuick.byteInputStream()) }
            .getOrElse {
                Toast.makeText(this, R.string.invalid_config, Toast.LENGTH_LONG).show()
                return
            }
        repo.saveConfig(config, TunnelRepository.DEFAULT_TUNNEL_NAME)
        builderCard.visibility = View.GONE
        editConfigText.setText(wgQuick)
        builderSummary.text = summarize(config)
        Toast.makeText(this, R.string.config_saved, Toast.LENGTH_SHORT).show()
    }

    private fun onRemoveConfig() {
        AlertDialog.Builder(this)
            .setTitle(R.string.remove_title)
            .setMessage(R.string.remove_message)
            .setPositiveButton(R.string.remove) { _, _ ->
                lifecycleScope.launch {
                    VpnManager.disconnect()
                    repo.clear()
                    restoreSavedConfig()
                }
            }
            .setNegativeButton(android.R.string.cancel, null)
            .show()
    }

    private fun restoreSavedConfig() {
        val config = repo.loadConfig()
        if (config == null) {
            builderCard.visibility = View.VISIBLE
            builderSummary.setText(R.string.no_config_hint)
            removeButton.visibility = View.GONE
        } else {
            builderSummary.text = summarize(config)
            removeButton.visibility = View.VISIBLE
        }
    }

    private fun summarize(config: com.wireguard.config.Config): String {
        val address = TunnelRepository.firstAddressOf(config) ?: getString(R.string.unknown)
        val endpoint = TunnelRepository.endpointOf(config) ?: getString(R.string.unknown)
        val dns = TunnelRepository.dnsOf(config)
        val mode = if (TunnelRepository.isFullTunnel(config)) {
            getString(R.string.mode_full)
        } else {
            getString(R.string.mode_split)
        }
        return getString(R.string.config_summary, address, endpoint, dns ?: "—", mode)
    }

    private fun formatBytes(bytes: Long): String {
        val kb = bytes / 1024.0
        val mb = kb / 1024.0
        val gb = mb / 1024.0
        return when {
            gb >= 1.0 -> String.format(Locale.US, "%.2f GB", gb)
            mb >= 1.0 -> String.format(Locale.US, "%.1f MB", mb)
            kb >= 1.0 -> String.format(Locale.US, "%.1f KB", kb)
            else -> "$bytes B"
        }
    }

    companion object {
        private const val REQUEST_VPN_CONSENT = 42
    }
}
