package cfd.ghostbin.ghostwebvpn

import android.content.Context
import com.wireguard.config.Config
import com.wireguard.config.InetNetwork
import com.wireguard.config.Peer
import java.net.InetAddress

/**
 * Persists the tunnel config the user imported, so the VPN can be
 * restored after a reboot or app restart without re-importing.
 */
class TunnelRepository(context: Context) {

    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun saveConfig(config: Config, name: String) {
        prefs.edit()
            .putString(KEY_WG_QUICK, config.toWgQuickString())
            .putString(KEY_NAME, name)
            .putBoolean(KEY_CONNECTED, true)
            .apply()
    }

    fun loadConfig(): Config? {
        val wgQuick = prefs.getString(KEY_WG_QUICK, null) ?: return null
        return runCatching { Config.parse(wgQuick.byteInputStream()) }.getOrNull()
    }

    fun configName(): String = prefs.getString(KEY_NAME, DEFAULT_TUNNEL_NAME) ?: DEFAULT_TUNNEL_NAME

    fun setConnected(connected: Boolean) {
        prefs.edit().putBoolean(KEY_CONNECTED, connected).apply()
    }

    fun wasConnected(): Boolean = prefs.getBoolean(KEY_CONNECTED, false)

    fun clear() {
        prefs.edit().clear().apply()
    }

    companion object {
        private const val PREFS_NAME = "ghost_web_vpn"
        private const val KEY_WG_QUICK = "wg_quick_config"
        private const val KEY_NAME = "tunnel_name"
        private const val KEY_CONNECTED = "connected"
        const val DEFAULT_TUNNEL_NAME = "ghost-web"

        /**
         * Builds a wg-quick config from the details of a Ghost endpoint
         * peer (as generated by server/docker-compose.yml).
         *
         * @param privateKey  peer (client) X25519 private key, Base64
         * @param address     tunnel address with prefix, e.g. "10.66.66.2/32"
         * @param dns         optional DNS server for the tunnel, e.g. "1.1.1.1"
         * @param serverPublicKey  server X25519 public key, Base64
         * @param endpoint    host[:port] of the WireGuard server, e.g. "203.0.113.7:51820"
         * @param allowedIps  comma-separated CIDRs, "0.0.0.0/0, ::/0" for full tunnel
         */
        fun buildWgQuickConfig(
            privateKey: String,
            address: String,
            dns: String?,
            serverPublicKey: String,
            endpoint: String,
            allowedIps: String
        ): String = buildString {
            appendLine("[Interface]")
            appendLine("PrivateKey = $privateKey")
            appendLine("Address = $address")
            dns?.takeIf { it.isNotBlank() }?.let { appendLine("DNS = $it") }
            appendLine()
            appendLine("[Peer]")
            appendLine("PublicKey = $serverPublicKey")
            appendLine("Endpoint = $endpoint")
            appendLine("AllowedIPs = $allowedIps")
            appendLine("PersistentKeepalive = 25")
        }

        /**
         * Generates a fresh X25519 keypair for the client.
         * @return Pair(base64PrivateKey, base64PublicKey)
         */
        fun generateKeypair(): Pair<String, String> {
            val privateKey = com.wireguard.crypto.Key.generatePrivateKey()
            val publicKey = privateKey.publicKey()
            return privateKey.toBase64() to publicKey.toBase64()
        }

        /**
         * Minimal standalone parser for the fields the builder screen needs,
         * so a user can paste their Ghost peer config and edit it.
         * Extracts privateKey, address, dns, peer public key, endpoint, allowed IPs.
         */
        fun parseWgQuickFields(wgQuick: String): Map<String, String> {
            val out = mutableMapOf<String, String>()
            var section = ""
            for (rawLine in wgQuick.lineSequence()) {
                val line = rawLine.substringBefore('#').trim()
                if (line.isEmpty()) continue
                if (line.startsWith("[")) {
                    section = line.substringAfter('[').substringBefore(']').trim().lowercase()
                    continue
                }
                val idx = line.indexOf('=')
                if (idx <= 0) continue
                val key = line.substring(0, idx).trim().lowercase()
                val value = line.substring(idx + 1).trim()
                when (key) {
                    "privatekey" -> out[FIELD_PRIVATE_KEY] = value
                    "address" -> out[FIELD_ADDRESS] = value
                    "dns" -> out[FIELD_DNS] = value
                    "publickey" -> if (section == "peer") out[FIELD_PEER_PUBLIC_KEY] = value
                    "endpoint" -> out[FIELD_ENDPOINT] = value
                    "allowedips" -> out[FIELD_ALLOWED_IPS] = value
                }
            }
            return out
        }

        /** Derives the tunnel address (first Address entry, IP + prefix) from a config. */
        fun firstAddressOf(config: Config): String? =
            config.getInterface().getAddresses().firstOrNull()?.let { addr: InetNetwork ->
                "${addr.address.hostAddress}/${addr.mask}"
            }

        /** Derives the peer endpoint "host:port" from a config. */
        fun endpointOf(config: Config): String? =
            config.getPeers().firstOrNull()?.let { peer: Peer ->
                val ep = peer.getEndpoint().orElse(null) ?: return null
                val host = ep.host
                val resolved = ep.resolved.orElse(null)
                val displayHost = if (host.contains(':') && resolved != null) {
                    // Wrap IPv6 literals in brackets for display
                    "[${resolved.hostAddress}]"
                } else {
                    host
                }
                "$displayHost:${ep.port}"
            }

        /** All configured DNS servers of the config, comma-joined. */
        fun dnsOf(config: Config): String? =
            config.getInterface().getDnsServers().joinToString(", ") { it.hostAddress }

        /** True when the tunnel routes the default IPv4 or IPv6 route. */
        fun isFullTunnel(config: Config): Boolean =
            config.getPeers().any { peer: Peer ->
                peer.getAllowedIps().any { it.mask == 0 }
            }

        /** The server public key of the first peer, or null. */
        fun serverPublicKeyOf(config: Config): String? =
            config.getPeers().firstOrNull()?.let { peer: Peer ->
                peer.getPublicKey().toBase64()
            }

        /** The client private key of the config, or null. */
        fun privateKeyOf(config: Config): String? =
            runCatching { config.getInterface().getPrivateKey().toBase64() }.getOrNull()

        /** Resolves a hostname for display purposes; returns the input on failure. */
        fun resolveHost(host: String): String =
            runCatching { InetAddress.getByName(host).hostAddress }.getOrNull() ?: host

        const val FIELD_PRIVATE_KEY = "private_key"
        const val FIELD_ADDRESS = "address"
        const val FIELD_DNS = "dns"
        const val FIELD_PEER_PUBLIC_KEY = "peer_public_key"
        const val FIELD_ENDPOINT = "endpoint"
        const val FIELD_ALLOWED_IPS = "allowed_ips"
    }
}
